services:
  q4xeunt97f:
    container_name: q4xeunt97f_app
    image: ghcr.io/mr-devloper005/obsidianimpacts.com:latest
    env_file:
      - .env
    network_mode: bridge
    restart: always
    ports:
      - "127.0.0.1:3066:3000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:3000/"]
      interval: 5m
      timeout: 3s
      retries: 2
